version: '3.4'

services:
  catalogdb:
   image: mongo

  basketdb:
   image: redis:alpine

  discountdb:
   image: postgres
    
  orderdb:
   image: mcr.microsoft.com/mssql/server:2017-latest
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  pgadmin:
    image: dpage/pgadmin4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Microservices/Catalog/Catalog.API/Dockerfile

  portainer:
    image: portainer/portainer-ce

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Microservices/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Microservices/Discount/Discount.API/Dockerfile

  dicount.grpc:
    image: ${DOCKER_REGISTRY-}dicountgrpc
    build:
      context: .
      dockerfile: Microservices/Discount/dicount.gRPC/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Microservices/Ordering/Ordering.API/Dockerfile

  apigatway:
    image: ${DOCKER_REGISTRY-}apigatway
    build:
      context: .
      dockerfile: APIGatWay/APIGatWay/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: APIGatWay/Shopping.Aggregator/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:






